Feature/80 staff page
vndbre/vndbre pull request #117
Opened 2022-04-06 12:28 UTC by Moltenship

2022-04-06 14:00 UTC, moetazaneta commented on src/api/dtos/characterDto.ts
>     * Character's sex (not gender); "m" (male), "f" (female) or "b" (both).
Perhaps, update jsdoc.

2022-04-06 14:00 UTC, moetazaneta commented on src/api/mappers/genderMapper.ts
> +  export const GENDER_FROM_DTO_MAP: Readonly<Record<GenderDto, Gender>> = {
I think it should be in a method `toGender`, like done in `Language` and `Staff`

2022-04-06 14:00 UTC, moetazaneta commented on src/features/Staff/components/StaffVisualNovelsTable/StaffVisualNovelsTable.tsx
> +  }, [] as ExtendedVisualNovel[]), [visualNovels, staffVisualNovels]);
Please use generic for reduce

2022-04-06 14:00 UTC, moetazaneta commented on src/features/Staff/components/StaffVisualNovelsTable/StaffVisualNovelsTable.tsx
> +              <Td><Link as={NavLink} to={`/vn/${vn.id}`}>{vn.title}</Link></Td>
I think, title should wrap too, test it with really really long one.

2022-04-06 14:00 UTC, moetazaneta commented on src/features/Staff/pages/StaffPage/StaffPage.tsx
> +      return staff.aliases.reduce((acc, cur) => {
Again with generic

2022-04-09 11:39 UTC, NightOfNights requested changes

2022-04-09 11:39 UTC, NightOfNights commented on src/features/Staff/components/StaffLinks/StaffLinks.tsx
> +  );
I think there is no profit in using `useMemo` since `links` is the only prop here and you are using `memo` for component already.

2022-04-09 11:39 UTC, NightOfNights commented on src/features/Staff/components/StaffVisualNovelsTable/StaffVisualNovelsTable.tsx
> +  }, []), [visualNovels, staffVisualNovels]);
Again, no profit from `useMemo`

2022-04-09 11:39 UTC, NightOfNights commented on src/features/Staff/components/StaffVisualNovelsTable/StaffVisualNovelsTable.tsx
> +          ))}
Let's move out it to constant, prefer keeping component template as simple as possible

2022-04-09 11:41 UTC, NightOfNights commented on src/features/Staff/components/StaffVisualNovelsTable/StaffVisualNovelsTable.tsx
> +interface ExtendedVisualNovel extends VisualNovel, StaffVisualNovel {}
Don't think this should be in UI layer

2022-04-09 13:41 UTC, Moltenship commented on src/api/mappers/genderMapper.ts
> +  export const GENDER_FROM_DTO_MAP: Readonly<Record<GenderDto, Gender>> = {
We should discuss it

2022-04-10 02:49 UTC, moetazaneta approved these changes

2022-04-10 06:50 UTC, NightOfNights approved these changes
Consider fetching data with sorting by released date like we discussed

2022-04-12 09:23 UTC, merged