Feature/4 overview tab
vndbre/vndbre pull request #33
Opened 2021-11-14 15:59 UTC by timofei-maximov-saritasa

2021-11-14 16:25 UTC, panov-aleksey-saritasa commented on src/api/index.ts
> +      refetchOnReconnect: false,
I don't think this setting should be global, it's better to make base config (and extend it if needed) and pass it into our custom useQuery hooks.

2021-11-14 16:25 UTC, panov-aleksey-saritasa commented on src/api/services/staffService.ts
> +
Remove pls, you can check fetch results via react query devtools

2021-11-14 16:25 UTC, panov-aleksey-saritasa commented on src/features/VisualNovel/components/CharacterCard/CharacterCard.tsx
> + */
Let's not write comments for props interface, only for props

2021-11-14 16:25 UTC, panov-aleksey-saritasa commented on src/features/VisualNovel/components/TagBlock/TagBlock.tsx
> +
Extra line

2021-11-14 16:25 UTC, panov-aleksey-saritasa commented on src/features/VisualNovel/pages/OverviewPage/OverviewPage.tsx
> +import ISO6391 from 'iso-639-1';
Maybe use alias for this module import?

2021-11-14 16:25 UTC, panov-aleksey-saritasa commented on src/features/VisualNovel/pages/OverviewPage/OverviewPage.tsx
> +            )}
Don't forget to refactor it 😄

2021-11-14 16:25 UTC, panov-aleksey-saritasa commented on src/utils/types/apiUrls.ts
> +  export const TAGS = 'tags';
Why uppercase?

2021-11-14 16:29 UTC, choi-moeta requested changes

2021-11-14 16:29 UTC, choi-moeta commented on src/api/index.ts
> +  baseURL: 'https://vndbre-proxy.azurewebsites.net/api/v1/',
Move out to constants or env.

2021-11-15 04:18 UTC, prekel commented on src/api/index.ts
> +  baseURL: 'https://vndbre-proxy.azurewebsites.net/api/v1/',
Will be done in #40

2021-11-15 08:08 UTC, prekel reviewed
lgtm

2021-11-15 08:10 UTC, prekel approved these changes
LGTM!!! 😉 🖖🖖🖖🖖

2021-11-15 08:52 UTC, choi-moeta requested changes

2021-11-15 08:52 UTC, moetazaneta commented on src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.tsx
> +              <Text>{data.description}</Text>
Add `white-space: break-spaces;` so it looks better 😉

2021-11-15 08:52 UTC, choi-moeta commented on package.json
> +    "@chakra-ui/icons": "^1.0.16",
Should be removed #16

2021-11-15 08:52 UTC, choi-moeta commented on src/api/dtos/characterDto.ts
> +  vns?: [number, number, number, string][];
I suggest move vn to separate interface, and properly doc it.

2021-11-15 08:52 UTC, choi-moeta commented on src/api/dtos/staffDto.ts
> +  aliases?: [number, string, string][];
separate and properly doc

2021-11-15 08:52 UTC, choi-moeta commented on src/features/VisualNovel/pages/OverviewPage/OverviewPage.module.css
> +
extra line

2021-11-15 08:52 UTC, choi-moeta commented on src/api/dtos/staffDto.ts
> +  description?: string | null;
Is it alright that type is `string | null | undefined`?

2021-11-15 08:52 UTC, choi-moeta commented on src/utils/types/apiUrls.ts
> +  export const TAGS = 'tags';
Why uppercase?

2021-11-21 11:28 UTC, panov-aleksey-saritasa requested changes

2021-11-21 11:28 UTC, panov-aleksey-saritasa commented on src/features/VisualNovel/pages/OverviewPage/OverviewPage.tsx
> +  };
So `publishers` state is updated per each release? How does it work? Maybe just create result object after all iterations and call `setPublishers` one time?

2021-11-21 11:28 UTC, panov-aleksey-saritasa commented on src/features/VisualNovel/pages/OverviewPage/OverviewPage.tsx
> +  const [publishers, setPublishers] = useState<Record<string, string[]>>(
Actually, as I see, `developers` and `publishers` are not state of the component, they are just dependable values that are calculated from `releases` data. Just create `const` variables from `fillDeveloperTeam` function. I think it should do the job.

2021-11-21 11:28 UTC, panov-aleksey-saritasa commented on src/features/VisualNovel/pages/OverviewPage/OverviewPage.tsx
> +          }
Are you sure this piece of code should be in template?

2021-11-21 13:25 UTC, NightOfNights requested changes

2021-11-21 13:25 UTC, NightOfNights commented on src/features/VisualNovel/components/CharacterCard/CharacterCard.tsx
> +          )
Why multiline?

2021-11-21 13:25 UTC, NightOfNights commented on src/features/VisualNovel/pages/OverviewPage/OverviewPage.tsx
> +  const [publishers, setPublishers] = useState<Record<string, string[]>>(
Actually, as I see, `developers` and `publishers` are not state of the component, they are just dependable values that are calculated from `releases` data. Just create `const` variables from `fillDeveloperTeam` function. I think it should do the job.

2021-11-21 13:25 UTC, NightOfNights commented on src/features/VisualNovel/pages/OverviewPage/OverviewPage.tsx
> +  };
So `publishers` state is updated per each release? How does it work? Maybe just create result object after all iterations and call `setPublishers` one time?

2021-11-21 13:25 UTC, NightOfNights commented on src/features/VisualNovel/pages/OverviewPage/OverviewPage.tsx
> +          }
Are you sure this piece of code should be in template?

2021-11-21 13:25 UTC, NightOfNights commented on src/utils/types/staffRoles.ts
> +};
Do you need `MappedStaffRoles` interface? Maybe just use `Record<StaffRoles, DisplayStaffRole>`?

2021-11-21 13:28 UTC, NightOfNights commented on src/api/mappers/visualNovelMapper.ts
> +};
I think `VisualNovelLength` enum should be used for switch cases, not for returning of values

2021-11-21 13:29 UTC, NightOfNights commented on src/api/mappers/visualNovelMapper.ts
> +};
Check how you did it in `src/utils/types/roles.ts` 😄

2021-11-29 04:05 UTC, choi-moeta approved these changes

2021-11-29 04:05 UTC, moetazaneta commented on src/models/staff.ts
> +  description?: string | null;
Again `null | undefined | string`

2021-11-30 15:27 UTC, NightOfNights approved these changes

2021-12-03 05:00 UTC, merged