feat: bbcode parsing (BBob)
vndbre/vndbre pull request #35
Opened 2021-11-14 16:57 UTC by prekel

2021-11-14 17:12 UTC, prekel commented
Ready for review now, but will be ready for merge after #33

2021-11-21 13:05 UTC, NightOfNights requested changes

2021-11-21 13:05 UTC, NightOfNights commented on src/components/BBCode/BBCode.tsx
> +import reactPreset from '@bbob/preset-react/es';
Create `t.d.ts` declaration file in the root of project and add:
 ```
declare module '@bbob/react/es/Component';
declare module '@bbob/preset-react/es';
 ```

2021-11-21 13:05 UTC, NightOfNights commented on src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.module.css
> +}
Remove pls

2021-11-21 13:05 UTC, NightOfNights commented on src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.module.css
> +}
Better create `BBCode.module.css` file to define styles for tags inside the component, for example,
```
.bbcode > a {
  ...
}

.bbcode > b {
 ...
}
```
and so on.

2021-11-21 13:05 UTC, NightOfNights commented on src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.module.css
> +}
I checked library API, you can pass style this way: 
```
import cls from './BBCode.module.css';

<BBCodeUntyped plugins={reactPreset()} componentProps={{ className: cls.bbcode }}>
```

2021-11-21 13:05 UTC, NightOfNights commented on src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.module.css
> +}
Also check how our links are styled in other components. But I'm not sure how to avoid copypasta of styles.

2021-11-25 11:11 UTC, prekel commented
I will close this PR. I will describe the details in #27

2021-12-05 15:25 UTC, closed without merging