Feature/25 baseurl
vndbre/vndbre pull request #40
Opened 2021-11-14 18:21 UTC by prekel

closes #25 closes #39

2021-11-15 04:13 UTC, choi-moeta requested changes

2021-11-15 04:13 UTC, choi-moeta commented on .env.production
> +VITE_VNDBRE_PROXY_BASEURL="https://vndbre-proxy.azurewebsites.net/api/v1/"
I think VNDBRE prefix is excessive, maybe just name it VITE_API_BASE_URL

2021-11-15 04:13 UTC, choi-moeta commented on package.json
> +    "@bbob/react": "^2.7.1",
bbob shouldn't be there

2021-11-15 04:13 UTC, choi-moeta commented on src/api/index.ts
> +  baseURL: import.meta.env.VITE_VNDBRE_PROXY_BASEURL as string,
There is a better way to add typings https://vitejs.dev/guide/env-and-mode.html#intellisense-for-typescript

2021-11-15 04:13 UTC, choi-moeta commented on .env.development
> +VITE_VNDBRE_PROXY_BASEURL="http://localhost:7879/api/v1/"
Developers don't have backend locally running

2021-11-15 04:15 UTC, choi-moeta commented on .env.development
> +VITE_VNDBRE_PROXY_BASEURL="http://localhost:7879/api/v1/"
I mean front-end developers

2021-12-06 09:38 UTC, NightOfNights approved these changes

2021-12-12 11:08 UTC, NightOfNights commented on README.md
> +### `npm dev`
`npm run dev`

2021-12-13 11:31 UTC, moetazaneta requested changes
I despise `dev-dev`.

2021-12-13 11:31 UTC, moetazaneta commented on package.json
> +    "dev-dev": "vite --mode development",
I suggest rename to `dev` and `dev:production`

2021-12-13 12:25 UTC, moetazaneta approved these changes

2021-12-13 12:37 UTC, merged