Make images clickable
vndbre/vndbre pull request #58
Opened 2021-12-16 13:53 UTC by Moltenship

Make images in visual novel media clickable #57

2021-12-19 12:07 UTC, NightOfNights commented on src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.tsx
> +            <Image src={data.image ?? undefined} loading="eager" alt={data.title} className={cls.image} />
Should we render image if there are no source?

2021-12-19 12:07 UTC, NightOfNights commented on src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.tsx
> +            <Image src={data.image ?? undefined} loading="eager" alt={data.title} className={cls.image} />
Maybe add placeholder

2021-12-19 12:07 UTC, NightOfNights commented on src/components/ImagePreviewDialog/ImagePreviewDialog.tsx
> +  </Modal>
I think it should be image carousel, instead of single image

2021-12-19 12:07 UTC, NightOfNights commented on src/components/ImagePreviewDialog/ImagePreviewDialog.tsx
> +  </Modal>
Maybe implement it somehow like [here](https://codesandbox.io/s/dd8vn?file=/src/ChakraCarousel.js)

2021-12-21 09:38 UTC, NightOfNights commented on src/components/ImagePreviewDialog/ImagePreviewDialog.tsx
> +  </Modal>
Nevermind, let's implement in another [task](https://github.com/vndbre/vndbre/issues/67)

2021-12-22 05:41 UTC, moetazaneta commented on src/features/VisualNovel/pages/MediaPage/MediaPage.module.css
>    width: 320px;
You should use design tokens.

2021-12-22 05:43 UTC, moetazaneta requested changes
use design tokens.

2022-02-12 11:08 UTC, moetazaneta approved these changes

2022-02-12 11:08 UTC, moetazaneta commented on src/features/VisualNovel/pages/MediaPage/MediaPage.tsx
> +          className={cls.image}
Remind you to use design tokens or chakra props!

2022-02-12 11:08 UTC, moetazaneta commented on src/features/VisualNovel/pages/MediaPage/MediaPage.tsx
> +        images={data.screens.filter(filterPredicate).map(screen => ({ src: screen.image }))}
Please, be mindful about code duplication.

2022-02-13 15:48 UTC, merged