feat: implement characters tab
vndbre/vndbre pull request #95
Opened 2022-02-13 15:50 UTC by Moltenship

2022-02-16 06:24 UTC, moetazaneta approved these changes

2022-02-17 14:43 UTC, prekel requested changes
![image](https://user-images.githubusercontent.com/19646569/154505052-ce9c6dbd-13e7-45f5-b13f-30f22d348975.png)

2022-02-19 05:55 UTC, NightOfNights requested changes

2022-02-19 05:55 UTC, NightOfNights commented on src/api/services/characterService.ts
> +export const fetchCharactersByVnId = async(vnId: string): Promise<Character[]> => {
Use `VisualNovel['id']` instead of `string`

2022-02-19 05:55 UTC, NightOfNights commented on src/api/services/characterService.ts
> +  return charactersChunk.flatMap(characterChunk => characterChunk.map(dto => characterFromDto(dto)));
Copy paste of https://github.com/vndbre/vndbre/blob/develop/src/api/services/releaseService.ts

2022-02-19 05:55 UTC, NightOfNights commented on src/features/VisualNovel/pages/CharactersPage/CharactersPage.tsx
> +      ) : <Text>No characters :(</Text>}
Is `:(` thing intended by designs?

2022-02-19 08:07 UTC, prekel requested changes
> `src/features/VisualNovel/pages/MediaPage/MediaPage.tsx(15,58): error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.`
Please fix compilation error.

2022-02-20 11:47 UTC, prekel requested changes
Please resolve conflicts.

2022-02-20 17:52 UTC, NightOfNights approved these changes

2022-02-21 13:06 UTC, merged